export const LOGIN_REQUEST = 'LOGIN/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN/LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN/LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP/SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP/SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP/SIGNUP_FAILURE'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = "APP/SHOW_ALERT"
export const HIDE_ALERT = "APP/HIDE_ALERT"